"""Phase 2A provisional initial batted-ball state parameters.

These coefficients generate physical initial conditions only. They are not yet
KBO-calibrated and are deliberately isolated from the Phase-1 plate-discipline
and the legacy HR/XBH result-resolution parameters.
"""

# Canonical units: exit velocity in mph, angles in degrees, timing normalized.
EXIT_VELOCITY_MIN_MPH = 30.0
EXIT_VELOCITY_MAX_MPH = 125.0
EXIT_VELOCITY_BASE_MPH = 72.0
EXIT_VELOCITY_QUALITY_GAIN_MPH = 25.0
EXIT_VELOCITY_POWER_GAIN_PER_POINT = 0.10
EXIT_VELOCITY_PITCH_SPEED_GAIN = 1.5
EXIT_VELOCITY_NOISE_SD_MPH = 6.0
EXIT_VELOCITY_QUALITY_NOISE_REDUCTION = 1.5

CONTACT_QUALITY_BASE = 0.52
CONTACT_QUALITY_CONTACT_GAIN_PER_POINT = 0.0025
CONTACT_QUALITY_HITTABLE_GAIN = 0.16
CONTACT_QUALITY_TIMING_PENALTY = 0.16
CONTACT_QUALITY_MOVEMENT_PENALTY = 0.05
CONTACT_QUALITY_LOCATION_GAIN = 0.02
CONTACT_QUALITY_NOISE_SD = 0.11

TIMING_MIN = -1.0
TIMING_MAX = 1.0
TIMING_PITCH_SPEED_SHIFT = -0.05
TIMING_HORIZONTAL_LOCATION_SHIFT = -0.05
TIMING_VERTICAL_LOCATION_SHIFT = -0.025
TIMING_BASE_SD = 0.34
TIMING_CONTACT_SD_PER_POINT = 0.0015
TIMING_SD_MIN = 0.22
TIMING_SD_MAX = 0.46

LAUNCH_ANGLE_MIN_DEG = -65.0
LAUNCH_ANGLE_MAX_DEG = 85.0
LAUNCH_ANGLE_BASE_DEG = 10.0
LAUNCH_ANGLE_VERTICAL_LOCATION_GAIN = -4.0
LAUNCH_ANGLE_QUALITY_GAIN = 6.0
LAUNCH_ANGLE_PROFILE_GAIN_PER_POINT = 0.025
LAUNCH_ANGLE_PROFILE_LIMIT_DEG = 3.5
LAUNCH_ANGLE_NOISE_BASE_SD_DEG = 16.0
LAUNCH_ANGLE_LOW_QUALITY_EXTRA_SD_DEG = 6.0

SPRAY_ANGLE_MIN_DEG = -75.0
SPRAY_ANGLE_MAX_DEG = 75.0
SPRAY_TIMING_GAIN_DEG = 27.0
SPRAY_HORIZONTAL_LOCATION_GAIN_DEG = -11.0
SPRAY_APPROACH_BIAS_DEG = 6.0
SPRAY_NOISE_SD_DEG = 13.0
FOUL_LINE_LEFT_DEG = -45.0
FOUL_LINE_RIGHT_DEG = 45.0
